source-file "${HOME}/.config/tmux/conf.d/base.tmux"
source-file "${HOME}/.config/tmux/conf.d/appearance.tmux"
source-file "${HOME}/.config/tmux/conf.d/keybinds.tmux"
source-file "${HOME}/.config/tmux/conf.d/plugins.tmux"
